# config.py
# ========================================================
# فەرهەنگی گەورەی زمانەکان (٥ زمان بە وەرگێڕانی ١٠٠٪ و ورد)
# ========================================================

LANG_DICT = {
    "Kurdish": {
        "title": "👑 ئیمپڕاتۆریەتی شاهانە",
        "subtitle": "گەورەترین سەکۆی مۆڵتی-بازرگانی بۆ سەرجەم خزمەتگوزارییەکان لە کوردستان",
        "home": "🏠 لاپەڕەی سەرەکی",
        "shop": "🛍️ بازاڕ و کەرەستەکان",
        "ad_portal": "📢 داواکردنی ڕیکلام",
        "login_btn": "🔑 دەروازەی ئەندامان",
        "choose_lang": "🌐 زمان هەڵبژێرە:",
        "biz_select": "🏢 جۆری کارەکەت زیاتر دیاری بکە:",
        "book_btn": "📅 نۆرە بگرە لەم بزنسە",
        "quick_order": "🛒 کڕینی خێرا",
        "username": "ئیمەیڵی فەرمی یان بازرگانی:",
        "password": "پاسۆردی پارێزراو:",
        "login_confirm": "چوونەژوورەوە بۆ ناو پلاتفۆڕم",
        "ad_title": "پۆرتالی ڕیکلامی شاهانە",
        "active_merchants": "🏢 ئەو بزنسانەی لەگەڵمان ئەکتیڤن",
        "staff_management": "👥 کارمەندەکان",
        "product_management": "📦 بەرهەمەکان",
        "booking_management": "📅 نۆرەکان و تۆمارەکان",
        "total_views": "کۆی گشتی بینینی لاپەڕەکانمان تا ئێستا",
        "no_merchant": "⚠️ هێشتا هیچ کام لە بزنسەکان و پیشەکان بۆ ئەم بەشە تۆمار نەکراوە.",
        "no_product": "⚠️ هیچ بەرهەمێک بۆ ئەم بەش و پیشەیە دیاری نەکراوە.",
        "plat_banner": "📢 پلاتفۆڕمی شاهانە: بەرهەمەکانت لێرە بەرز بکەرەوە بۆ ئەوەی زۆرترین فرۆشتنت هەبێت!",
        "ad_intro": "لێرەوە داوای ڕیکلامی سپۆنسەری شاهانە بکە بۆ بزنسەکەت:",
        "fullname": "ناوی بەڕێزت:",
        "bizname": "ناوی بزنسەکەت یان کۆمپانیاکەت:",
        "phone_whats": "ژمارەی مۆبایل / واتساپ:",
        "ad_text": "دەقی ڕیکلامی خوازراو:",
        "ad_link": "بەستەری فەرمی ڕیکلام (فەیسبووک، ئینستاگرام، ماڵپەڕ):",
        "ad_duration": "ماوەی چالاک مانەوە بە مانگ:",
        "ad_submit": "ناردنی داواکاری بۆ دەستەی شاهانە",
        "success_ad": "داواکارییەکەت بە سەرکەوتوویی نێردرا! دوای پێداچوونەوەی ئەدمین بڵاودەبێتەوە. 🎉",
        "fill_fields": "تکایە خانە پێویستەکان بە دروستی پڕ بکەرەوە!",
        "reg_banner": "بزنسەکەت لێرەوە تۆمار بکە بۆ ئەوەی زیاتر بەناوبانگ بیت لە وێبسایتی جیهانی شاهانە 🚀",
        "reg_btn": "تۆمارکردنی بزنسی نوێ",
        "owner_name": "ناوی تەواوی خاوەن کار:",
        "biz_sec": "بزنسەکەت سەر بە کام بەشەیە؟",
        "country": "وڵات:",
        "city": "شار:",
        "address": "ناونیشانی فیزیکی ورد:",
        "reg_submit": "دروستکردنی ئەکاونتی نوێ و تۆمارکردن",
        "reg_success": "پیرۆزە! ئەکاونتی بازرگانیت بە سەرکەوتوویی دروستکرا. ئێستا دەتوانیت بچیتە ژوورەوە. 🎉",
        "email_exists": "⚠️ ئەم ئیمەیڵە پێشتر لە سیستەمدا بەکارهێنراوە!",
        "finance_tab": "💰 ژووری دارایی تایبەت",
        "search_label": "🔍 بگەڕێ بۆ بەرهەم یان بزنس لە وێبسایتی شاهانە:",
        "contact_admin": "📞 پەیوەندی بە دەستەی بەڕێوەبەرایەتی و ئەدمینەکانەوە بکە لە ڕێگەی واتساپەوە:"
    },
    "English": {
        "title": "👑 Royal Empire",
        "subtitle": "The largest multi-merchant platform for all services in Kurdistan",
        "home": "🏠 Home Page",
        "shop": "🛍️ Market & Products",
        "ad_portal": "📢 Request Advertisement",
        "login_btn": "🔑 Member Portal",
        "choose_lang": "🌐 Choose Language:",
        "biz_select": "🏢 Select Your Business Type:",
        "book_btn": "📅 Book an Appointment",
        "quick_order": "🛒 Quick Buy",
        "username": "Official or Business Email:",
        "password": "Secure Password:",
        "login_confirm": "Login to Platform",
        "ad_title": "Royal Advertising Portal",
        "active_merchants": "🏢 Active Businesses on Platform",
        "staff_management": "👥 Staff Members",
        "product_management": "📦 Products",
        "booking_management": "📅 Bookings & Records",
        "total_views": "Total Page Views Till Now",
        "no_merchant": "⚠️ No businesses are registered in this category yet.",
        "no_product": "⚠️ No products are currently listed for this business/category.",
        "plat_banner": "📢 Royal Platform: Elevate your products here for maximum reach!",
        "ad_intro": "Request your Royal Sponsored Ad here for your business:",
        "fullname": "Your Full Name:",
        "bizname": "Your Business or Company Name:",
        "phone_whats": "Mobile Number / WhatsApp:",
        "ad_text": "Desired Ad Content Text:",
        "ad_link": "Official Ad Link (Facebook, Instagram, Web):",
        "ad_duration": "Duration in Months:",
        "ad_submit": "Send Request to Royal Board",
        "success_ad": "Your request has been successfully submitted! It will appear once approved by admin. 🎉",
        "fill_fields": "Please fill all required fields correctly!",
        "reg_banner": "Register your business here to become famous on the Royal International Website 🚀",
        "reg_btn": "Register New Business",
        "owner_name": "Full Name of Business Owner:",
        "biz_sec": "Which section does your business belong to?",
        "country": "Country:",
        "city": "City:",
        "address": "Detailed Physical Address:",
        "reg_submit": "Create New Account & Register",
        "reg_success": "Congratulations! Your merchant account has been created successfully. You can log in now. 🎉",
        "email_exists": "⚠️ This email has already been registered in our system!",
        "finance_tab": "💰 Special Finance Chamber",
        "search_label": "🔍 Search for products or businesses on Royal Website:",
        "contact_admin": "📞 Contact the Executive Board & Admins via WhatsApp:"
    },
    "Arabic": {
        "title": "👑 الإمبراطورية الملكية",
        "subtitle": "أكبر منصة متعددة التجار لجميع الخدمات في كوردستان",
        "home": "🏠 الصفحة الرئيسية",
        "shop": "🛍️ السوق والمنتجات",
        "ad_portal": "📢 طلب إعلان",
        "login_btn": "🔑 بوابة الأعضاء",
        "choose_lang": "🌐 اختر اللغة:",
        "biz_select": "🏢 حدد نوع عملك التجاري:",
        "book_btn": "📅 احجز موعداً",
        "quick_order": "🛒 شراء سريع",
        "username": "البريد الإلكتروني الرسمي أو التجاري:",
        "password": "كلمة المرور الآمنة:",
        "login_confirm": "تسجيل الدخول إلى المنصة",
        "ad_title": "البوابة الإعلانية الملكية",
        "active_merchants": "🏢 الأعمال النشطة معنا",
        "staff_management": "👥 إدارة الموظفين",
        "product_management": "📦 المنتجات",
        "booking_management": "📅 الحجوزات والسجلات",
        "total_views": "إجمالي زيارات الصفحة حتى الآن",
        "no_merchant": "⚠️ لم يتم تسجيل أي أعمال في هذا القسم حتى الآن.",
        "no_product": "⚠️ لا توجد منتجات معروضة لهذا القسم أو النشاط حالياً.",
        "plat_banner": "📢 المنصة الملكية: سوّق لمنتجاتك هنا لتحقيق أعلى مبيعات ممكنة!",
        "ad_intro": "اطلب إعلانك الممول والمدعوم من الملكية لنشاطك التجاري من هنا:",
        "fullname": "اسمك الكامل الموقر:",
        "bizname": "اسم نشاطك التجاري أو شركتك:",
        "phone_whats": "رقم الهاتف / الواتساب الخاص بك:",
        "ad_text": "نص الإعلان المطلوب:",
        "ad_link": "رابط الإعلان الرسمي (فيسبوك، إنستغرام، موقع الكتروني):",
        "ad_duration": "مدة الإعلان بالأشهر:",
        "ad_submit": "إرسال الطلب إلى الإدارة الملكية",
        "success_ad": "تم إرسال طلبك بنجاح! سيتم تفعيله بعد مراجعة المسؤولين والموافقة عليه. 🎉",
        "fill_fields": "يرجى ملء جميع الحقول المطلوبة بشكل صحيح تماماً!",
        "reg_banner": "سجل عملك التجاري هنا لتنال شهرة أوسع على الموقع الإلكتروني العالمي الملكي 🚀",
        "reg_btn": "تسجيل نشاط تجاري جديد",
        "owner_name": "الاسم الكامل لمالك العمل:",
        "biz_sec": "إلى أي قسم ينتمي عملك التجاري؟",
        "country": "البلد:",
        "city": "المدينة:",
        "address": "العنوان الفعلي التفصيلي:",
        "reg_submit": "إنشاء حساب جديد والتسجيل",
        "reg_success": "تهانينا! تم إنشاء حساب التاجر الخاص بك بنجاح. يمكنك الآن تسجيل الدخول. 🎉",
        "email_exists": "⚠️ هذا البريد الإلكتروني مسجل بالفعل في نظامنا سابقاً!",
        "finance_tab": "💰 الغرفة المالية الخاصة",
        "search_label": "🔍 ابحث عن المنتجات أو الشركات على موقع الملكية الإلكتروني:",
        "contact_admin": "📞 تواصل مع الهيئة التنفيذية والمسؤولين مباشرة عبر الواتساب:"
    },
    "Turkish": {
        "title": "👑 Kraliyet İmparatorluğu",
        "subtitle": "Kürdistan'daki tüm hizmetler için en büyük çoklu üye platformu",
        "home": "🏠 Ana Sayfa",
        "shop": "🛍️ Mağaza ve Ürünler",
        "ad_portal": "📢 Reklam Başvurusu",
        "login_btn": "🔑 Üye Girişi",
        "choose_lang": "🌐 Dil Seçiniz:",
        "biz_select": "🏢 İşletme Türünüzü Belirleyin:",
        "book_btn": "📅 Randevu Al",
        "quick_order": "🛒 Hızlı Satın Al",
        "username": "Resmi veya Ticari E-posta:",
        "password": "Güvenli Şifre:",
        "login_confirm": "Platforma Giriş Yap",
        "ad_title": "Kraliyet Reklam Portalı",
        "active_merchants": "🏢 Platformdaki Aktif İşletmeler",
        "staff_management": "👥 Personel Yönetimi",
        "product_management": "📦 Ürünler",
        "booking_management": "📅 Randevular ve Kayıtlar",
        "total_views": "Şu Ana Kadarki Toplam Sayfa Görüntüleme",
        "no_merchant": "⚠️ Bu kategoride henüz kayıtlı bir işletme bulunmamaktadır.",
        "no_product": "⚠️ Bu bölüm veya işletme için henüz bir ürün listelenmemiştir.",
        "plat_banner": "📢 Kraliyet Platformu: En yüksek erişim için ürünlerinizi burada öne çıkarın!",
        "ad_intro": "İşletmeniz için Kraliyet Sponsorlu Reklam talebini buradan iletin:",
        "fullname": "Adınız Soyadınız:",
        "bizname": "İşletmenizin veya Şirketinizin Adı:",
        "phone_whats": "Telefon Numarası / WhatsApp:",
        "ad_text": "İstenen Reklam Metni İçeriği:",
        "ad_link": "Resmi Reklam Bağlantısı (Facebook, Instagram, Web):",
        "ad_duration": "Aylık Süre Uzunluğu:",
        "ad_submit": "Kraliyet Kuruluna Başvuru Gönder",
        "success_ad": "Talebiniz başarıyla gönderildi! Yönetici onayından sonra yayına alınacaktır. 🎉",
        "fill_fields": "Lütfen gerekli alanları eksiksiz ve doğru doldurun!",
        "reg_banner": "İşletmenizi buradan kaydedin ve Kraliyet Uluslararası Web Sitesinde daha fazla tanının 🚀",
        "reg_btn": "Yeni İşletme Kaydı",
        "owner_name": "İşletme Sahibinin Tam Adı:",
        "biz_sec": "İşletmeniz hangi bölüme ait?",
        "country": "Ülke:",
        "city": "Şehir:",
        "address": "Detaylı Fiziksel Adres:",
        "reg_submit": "Yeni Hesap Oluştur ve Kaydol",
        "reg_success": "Tebrikler! Mağaza hesabınız başarıyla oluşturuldu. Şimdi giriş yapabilirsiniz. 🎉",
        "email_exists": "⚠️ Bu e-posta adresi sistemimizde zaten kayıtlıdır!",
        "finance_tab": "💰 Özel Finans Odası",
        "search_label": "🔍 Kraliyet Web Sitesinde ürün veya işletme arayın:",
        "contact_admin": "📞 WhatsApp üzerinden Yönetim Kurulu ve Yöneticilerle iletişime geçin:"
    },
    "Persian": {
        "title": "👑 امپڕاتۆریەتی شاهانە",
        "subtitle": "بزرگترین پلتفرم چندفروشگاهی برای تمامی خدمات در کردستان",
        "home": "🏠 صفحه اصلی",
        "shop": "🛍️ بازاڕ و کەرەستەکان",
        "ad_portal": "📢 ثبت درخواست تبلیغات",
        "login_btn": "🔑 پرتال اعضا",
        "choose_lang": "🌐 انتخاب زبان:",
        "biz_select": "🏢 نوع کسب‌وکار خود را مشخص کنید:",
        "book_btn": "📅 ثبت نوبت و رزرو",
        "quick_order": "🛒 خرید سریع",
        "username": "ایمیل رسمی یا تجاری:",
        "password": "رمز عبور ایمن:",
        "login_confirm": "ورود به سیستم پلتفرم",
        "ad_title": "پورتال تبلیغاتی سلطنتی",
        "active_merchants": "🏢 کسب‌وکارهای فعال در پلتفرم",
        "staff_management": "👥 مدیریت پرسنل",
        "product_management": "📦 محصولات",
        "booking_management": "📅 مدیریت نوبت‌ها و دفاتر",
        "total_views": "کل بازدید صفحات تا این لحظه",
        "no_merchant": "⚠️ هنوز هیچ کسب‌وکاری در این دسته ثبت نشده است.",
        "no_product": "⚠️ هیچ محصولی برای این بخش یا صنف در حال حاضر ثبت نشده است.",
        "plat_banner": "📢 پلتفرم سلطنتی: محصولات خود را در اینجا ارتقا دهید تا بیشترین فروش را داشته باشید!",
        "ad_intro": "درخواست تبلیغات حامی مالی سلطنتی خود را برای کسب‌وکارتان ثبت کنید:",
        "fullname": "نام کامل شما:",
        "bizname": "نام کسب‌وکار یا شرکت شما:",
        "phone_whats": "شماره همراه / واتس‌اپ:",
        "ad_text": "متن تبلیغاتی مورد نظر:",
        "ad_link": "لینک رسمی تبلیغ (فیسبوک، اینستاگرام، وب‌سایت):",
        "ad_duration": "مدت زمان فعال بودن به ماه:",
        "ad_submit": "ارسال درخواست به هیئت سلطنتی",
        "success_ad": "درخواست شما با موفقیت ارسال شد! پس از تایید مدیر منتشر خواهد شد. 🎉",
        "fill_fields": "لطفاً تمامی فیلدهای الزامی را به درستی تکمیل کنید!",
        "reg_banner": "کسب‌وکار خود را در اینجا ثبت کنید تا در وب‌سایت بین‌المللی سلطنتی مشهورتر شوید 🚀",
        "reg_btn": "ثبت کسب‌وکار جدید",
        "owner_name": "نام کامل مالک کسب‌وکار:",
        "biz_sec": "کسب‌وکار شما متعلق به کدام بخش است؟",
        "country": "کشور:",
        "city": "شهر:",
        "address": "آدرس فیزیکی دقیق:",
        "reg_submit": "ایجاد حساب کاربری جدید و ثبت نام",
        "reg_success": "تبریک! حساب تجاری شما با موفقیت ایجاد شد. اکنون می‌توانید وارد شوید. 🎉",
        "email_exists": "⚠️ این ایمیل قبلاً در سیستم ثبت شده است!",
        "finance_tab": "💰 اتاق مالی اختصاصی",
        "search_label": "🔍 جستجوی محصولات یا کسب‌وکارها در وب‌سایت سلطنتی:",
        "contact_admin": "📞 تماس با هیئت اجرایی و مدیران از طریق واتس‌اپ:"
    }
}
